x1=int(input("Enter x1 value = "))
x2=int(input("Enter x2 value = "))
y1=int(input("Enter y1 value = "))
y2=int(input("Enter y2 value = "))
midpoint=((x1+x2)/2,(y1+y2)/2)
print("Midpoint = ",midpoint)
